name: Deploy Bot

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mybot:latest .

      - name: Deploy to VDS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VDS_HOST }}
          username: deploy
          key: ${{ secrets.VDS_SSH_KEY }}
          script: |
            cd ~/bot || git clone git@github.com:USERNAME/REPO.git ~/bot
            cd ~/bot
            git pull origin main
            docker build -t mybot:latest .
            docker stop mybot || true
            docker rm mybot || true
            docker run -d --name mybot --restart always mybot:latest
