name: Deploy Bot

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mybot:latest .

      - name: Deploy to VDS
        uses: appleboy/ssh-action@v1.0.0
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          SPREADSHEET_NAME: ${{ secrets.SPREADSHEET_NAME }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
          CREDENTIALS_JSON_B64: ${{ secrets.CREDENTIALS_JSON_B64 }}
        with:
          host: ${{ secrets.VDS_HOST }}
          username: deploy
          key: ${{ secrets.VDS_SSH_KEY }}
          envs: TELEGRAM_BOT_TOKEN,SPREADSHEET_NAME,ADMIN_ID,CREDENTIALS_JSON_B64
          script: |
            cd ~/bot
            git pull origin main
            echo "${CREDENTIALS_JSON_B64}" | base64 -d > credentials.json
            docker build -t mybot:latest .
            docker stop mybot || true
            docker rm mybot || true
            docker run -d \
              --name mybot \
              --restart always \
              -e TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN}" \
              -e SPREADSHEET_NAME="${SPREADSHEET_NAME}" \
              -e ADMIN_ID="${ADMIN_ID}" \
              -e CREDENTIALS_FILE="./credentials.json" \
              -v $(pwd)/credentials.json:/app/credentials.json \
              mybot:latest
